### PR TITLE
Chart version updated -> 0.1.1

### PR DESCRIPTION
**Pull request by evmos-lde**
As I can see from the fixes here: [GitHub Commit](https://github.com/cloudflare/helm-charts/commit/c53b4b314999baaab0402f39173bbc6e3b9d7b29), the chart version has not been updated :-(

Could you please increment the chart version and create new packages? Thank you!

Feel free to use this improved version :)

### CODE REVIEW

**Comment by evmos-lde** [comment]
@bwesterb Can review?

**Comment by evmos-lde** [comment]
@bwesterb can you please review?

**Comment by denzhel** [comment]
We need this as well :)

**Comment by evmos-lde** [comment]
I have also disabled the auto-update of the binary in this PR. @bwesterb @obezuk — could you please, please, please review this? Thank you!

image

**Review by uhthomas — APPROVED** [review]

**Comment by uhthomas** [comment]
I would prefer to keep the auto-update PR separate (https://github.com/cloudflare/helm-charts/pull/51), but it is what it is.

**Review by obezuk — APPROVED** [review]
Hi folks, just got back from leave and catching up on this. This looks good and makes sense to disable auto update as the cloudflared version is tied to the chart.

**Pull request merged**
